/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_server;

import java.io.IOException;
import java.net.ServerSocket;

public class App {
    public static void main(String[] args) throws IOException {
        int port = 5000;
        String directory = "/Users/victorelizalde/Documents/Github/cob_spec/public";
        Server server = new Server(port, directory);
        server.runServer();
    }
}
