/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_server;

import java.io.IOException;
import java.net.ServerSocket;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class App {
    public static void main(String[] args) throws IOException {
        String directory = Constants.DEFAULT_SERVER_DIRECTORY;
        Server server = new Server(Constants.DEFAULT_PORT, directory);
        server.runServer();
    }
}
