/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_server;

import org.junit.Test;
import org.junit.Before;
import java.net.*;
import java.io.*;

import static org.junit.Assert.*;

public class AppTest {

}
